name: Lint Java
description: Lints Java code using Checkstyle

inputs:
  app-path:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.app-path }}"
        ./gradlew checkstyleMain || ./mvnw checkstyle:check || echo "Checkstyle not configured"
      shell: bash
