name: "Notify MS Teams"
description: "Sends notification to MS Teams"

inputs:
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: MS Teams Notify
      uses: aliencube/microsoft-teams-actions@v0.9.0
      with:
        webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
        message: ${{ inputs.message }}
