name: "Notify Slack"
description: "Sends notification to Slack"

inputs:
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: Slack Notify
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "${{ inputs.message }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}