name: "Sentry Monitoring"
description: "Creates Sentry release and deploy"

inputs:
  app-path:
    required: false
    description: string

runs:
  using: "composite"
  steps:
    - name: Sentry Release Tracking
      uses: getsentry/action-release@v1
      with:
        environment: production
        sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
        sentry_org: ${{ secrets.SENTRY_ORG }}
        sentry_project: ${{ secrets.SENTRY_PROJECT }}
        version: ${{ github.sha }}