name: Lint Node.js
description: Lints Node.js code using ESLint

inputs:
  app-path:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.app-path }}"
        npm ci || yarn install
        npx eslint . --ext .js,.ts
      shell: bash
