name: Lint C++

inputs:
  working-directory:
    required: false
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update && sudo apt-get install -y clang-tidy
        find . -name '*.cpp' -o -name '*.cc' | xargs -r clang-tidy || true
      shell: bash
      working-directory: ${{ inputs.working-directory }}
