name: "Build and Push Docker Image (Delegator)"
description: "Builds and pushes Docker image using docker/build-push-action"

inputs:
  app-path:
    required: true
    description: string
  image-name:
    required: true
    description: string
  tag:
    required: false
    default: "latest"
    description: string

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.app-path }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}

