name: 'Build Docker Image'
description: 'Reusable build-image action for any app'

inputs:
  working-directory:
    required: false
    default: '.'
    description: 'Directory containing the Dockerfile'
  environment:
    required: false
    default: 'dev'
    description: 'Environment (dev, uat, stag, prod)'

outputs:
  image-tag:
    description: 'Docker image tag used'
    value: ${{ steps.set-tag.outputs.image_tag }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Image Tag
      id: set-tag
      shell: bash
      run: |
        if [ "${{ inputs.environment }}" == "prod" ]; then
          TAG="v$(date +%Y%m%d%H%M%S)"
        else
          TAG="${{ inputs.environment }}-$(git rev-parse --short HEAD)"
        fi
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      shell: bash
      run: |
        cd "${{ inputs.working-directory }}"
        docker build \
          --build-arg APP_ENV=${{ inputs.environment }} \
          -t myapp:${{ steps.set-tag.outputs.image_tag }} \
          .

