name: "Build Image Delegator"
description: "Delegates Docker image build to the correct stack-specific action"

inputs:
  app-path:
    required: true
    description: string
  image-name:
    required: true
    description: string
  framework:
    required: true
    description: string
  tag:
    required: false
    description: string
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Build Next.js Docker image
      if: ${{ contains(inputs.framework, 'nextjs') }}
      uses: ./nextjs
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}

    - name: Build Nuxt.js Docker image
      if: ${{ contains(inputs.framework, 'nuxtjs') }}
      uses: ./nuxtjs
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}

    - name: Build fallback
      if: ${{ !contains('nextjs,nuxtjs', inputs.framework) }}
      run: echo "No Docker build configured for ${{ inputs.framework }}."
      shell: bash