name: Continuous Deployment

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      environment:
        required: true
        type: string
      artifact-tag:
        required: true
        type: string
      strategy:
        required: false
        type: string
        default: 'rolling'
      infra:
        required: false
        type: string
        default: 'kubernetes'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: ./.github/actions/deploy
        with:
          environment: ${{ inputs.environment }}
          image-tag: ${{ inputs.artifact-tag }}
          strategy: ${{ inputs.strategy }}
          platform: ${{ inputs.infra }}

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Slack Notification
        uses: ./.github/actions/notify
        with:
          title: "Deployment Finished"
          message: "Deployed image `${{ inputs.artifact-tag }}` to `${{ inputs.environment }}`."
          status: ${{ needs.deploy.result }}
          environment: ${{ inputs.environment }}
