name: "Deploy Delegator"
description: "Deploys to Kubernetes, Docker Swarm, AWS EC2, etc."
inputs:
  platform:
    required: true
    description: string
  app-path:
    required: true
    description: string
  image-name:
    required: true
    description: string
  tag:
    required: false
    default: "latest"
    description: string
  environment:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: Deploy to Kubernetes
      if: ${{ inputs.platform == 'kubernetes' || inputs.platform == 'eks' }}
      uses: azure/k8s-deploy@v5
      with:
        action: deploy
        manifests: |
          ${{ inputs.app-path }}/k8s/deployment.yaml
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
        namespace: ${{ inputs.environment }}

    - name: Deploy to Docker Swarm
      if: ${{ inputs.platform == 'swarm' }}
      run: |
        docker stack deploy -c ${{ inputs.app-path }}/docker-stack.yml ${{ inputs.image-name }}
      shell: bash

    - name: Deploy to AWS EC2
      if: ${{ inputs.platform == 'ec2' }}
      run: |
        echo "Custom EC2 deployment script here"
        # scp/docker-compose up/ssh etc.
      shell: bash

    - name: Skipped
      if: ${{ !contains('kubernetes,eks,swarm,ec2', inputs.platform) }}
      run: echo "No deploy routine configured for ${{ inputs.platform }}."
      shell: bash
