name: "Deploy Delegator"
description: "Delegates deploy to the correct stack/platform-specific action"

inputs:
  platform:
    required: true
    description: string
  app-path:
    required: true
    description: string
  image-name:
    required: true
    description: string
  framework:
    required: true
    description: string
  tag:
    required: false
    description: string
    default: "latest"
  environment:
    description: string
    required: true
  stack-name:
    required: false
    description: string
  docker-host:
    required: false
    description: string
  docker-username:
    required: false
    description: string
  docker-password:
    required: false
    description: string

runs:
  using: "composite"
  steps:
    - name: Deploy Next.js to Kubernetes
      if: ${{ contains(inputs.framework, 'nextjs') && (inputs.platform == 'kubernetes' || inputs.platform == 'eks') }}
      uses: ./nextjs-k8s
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}

    - name: Deploy Nuxt.js to Kubernetes
      if: ${{ contains(inputs.framework, 'nuxtjs') && (inputs.platform == 'kubernetes' || inputs.platform == 'eks') }}
      uses: ./nuxtjs-k8s
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}

    - name: Deploy to Docker Swarm
      if: ${{ inputs.platform == 'swarm' }}
      uses: ./docker-swarm
      with:
        app-path: ${{ inputs.app-path }}
        stack-name: ${{ inputs.stack-name }}
        docker-host: ${{ inputs.docker-host }}
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}

    - name: Deploy fallback
      if: ${{ !contains('nextjs,nuxtjs', inputs.framework) || !(inputs.platform == 'kubernetes' || inputs.platform == 'eks') }}
      run: echo "No deploy routine configured for ${{ inputs.framework }} to ${{ inputs.platform }}."
      shell: bash
