name: "Deploy Delegator"
description: "Delegates deploy to the correct stack/platform-specific action"

inputs:
  platform:
    required: true
    description: string
  app-path:
    required: true
    description: string
  image-name:
    required: true
    description: string
  tag:
    required: false
    description: string
    default: "latest"
  environment:
    description: string
    required: true
  stack-name:
    required: false
    description: string
  docker-host:
    required: false
    description: string
  docker-username:     # Docker Swarm only
    required: false
    description: string
  docker-password:
    required: false
    description: string
  region:
    required: true
  cluster_name:
    required: true
  project_id:
    required: false    # GCP only
  resource_group:
    required: false    # Azure only

runs:
  using: "composite"
  steps:
    - name: Deploy to AWS EC2
      if: ${{ inputs.platform == 'ec2' }}
      uses: ./deploy-ec2
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}

    - name: Deploy to AWS EKS
      if: ${{ inputs.platform == 'eks' }}
      uses: ./aws-eks
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}

    - name: Deploy to GCP GKE
      if: ${{ inputs.platform == 'gke' }}
      uses: ./deploy-gke
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        region: ${{ inputs.region }}
        cluster_name: ${{ inputs.cluster_name }}
        project_id: ${{ inputs.project_id }}

    - name: Deploy to Azure AKS
      if: ${{ inputs.platform == 'aks' }}
      uses: ./deploy-aks
      with:
        app-path: ${{ inputs.app-path }}
        image-name: ${{ inputs.image-name }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        region: ${{ inputs.region }}
        cluster_name: ${{ inputs.cluster_name }}
        resource_group: ${{ inputs.resource_group }}

    - name: Deploy to Docker Swarm
      if: ${{ inputs.platform == 'swarm' }}
      uses: ./deploy-swarm
      with:
        app-path: ${{ inputs.app-path }}
        stack-name: ${{ inputs.stack-name }}
        docker-host: ${{ inputs.docker-host }}
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}

    - name: Deploy fallback
      if: ${{ !contains('eks,gke,aks,swarm,ec2', inputs.platform) }}
      run: echo "No deploy routine configured for ${{ inputs.platform }}."
      shell: bash

