apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-backend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-backend
  template:
    metadata:
      labels:
        app: your-backend
    spec:
      containers:
        - name: your-backend
          image: ghcr.io/YOUR_ORG/your-backend:latest
          ports:
            - containerPort: 8080