apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxtjs-app
  labels:
    app: nuxtjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxtjs-app
  template:
    metadata:
      labels:
        app: nuxtjs-app
    spec:
      containers:
        - name: nuxtjs-app
          image: ghcr.io/your-repo/nuxtjs:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nuxtjs-app
spec:
  selector:
    app: nuxtjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000