name: CI - Nuxt

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev, feature/**]

jobs:
  ci:
    uses: './.github/workflows/ci.yml'
    with:
      working-directory: '.'
      environment: 'dev'
