name: "Notify Discord"
description: "Sends notification to Discord"

inputs:
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: Discord Notify
      uses: Ilshidur/action-discord@v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: ${{ inputs.message }}