name: "Notify PagerDuty"
description: "Sends alert to PagerDuty"

inputs:
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: PagerDuty Alert
      uses: pagerduty/pagerduty-action@v1
      with:
        routing_key: ${{ secrets.PAGERDUTY_KEY }}
        summary: ${{ inputs.message }}
        source: github-actions
        severity: info