name: Notify PagerDuty

inputs:
  message:
    required: true
  title:
    required: false
    default: "CI Notification"
  status:
    required: false
    default: "info"
  environment:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        curl -X POST https://events.pagerduty.com/v2/enqueue \
          -H "Content-Type: application/json" \
          -d '{
            "routing_key": "${{ secrets.PAGERDUTY_ROUTING_KEY }}",
            "event_action": "trigger",
            "payload": {
              "summary": "${{ inputs.title }}: ${{ inputs.message }}",
              "source": "GitHub Actions",
              "severity": "${{ inputs.status }}",
              "custom_details": {
                "Environment": "${{ inputs.environment }}",
                "Status": "${{ inputs.status }}"
              }
            }
          }'
      shell: bash
