name: Notify Email

inputs:
  message:
    required: true
  title:
    required: false
    default: "CI Notification"
  status:
    required: false
    default: "info"
  environment:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "${{ inputs.title }} - ${{ inputs.status }}"
        to: ${{ secrets.EMAIL_RECIPIENTS }}
        from: GitHub CI/CD
        body: |
          Environment: ${{ inputs.environment }}
          Status: ${{ inputs.status }}

          ${{ inputs.message }}
