name: "Notify Email"
description: "Sends notification email"

inputs:
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: Email Notify
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "CI/CD Notification"
        body: ${{ inputs.message }}
        to: ${{ secrets.EMAIL_TO }}
        from: "ci-cd@yourdomain.com"
