name: Lint Python
description: Lints Python code using flake8

inputs:
  app-path:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.app-path }}"
        pip install flake8
        flake8 .
      shell: bash
