name: Lint Python

inputs:
  working-directory:
    required: false
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      working-directory: ${{ inputs.working-directory }}

    - name: Install flake8
      run: pip install flake8
      working-directory: ${{ inputs.working-directory }}

    - name: Run flake8
      run: flake8 .
      shell: bash
      working-directory: ${{ inputs.working-directory }}
