name: Lint Go
description: Lints Go code

inputs:
  app-path:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.app-path }}"
        go fmt ./...
        go vet ./...
      shell: bash
