name: Lint Go

inputs:
  working-directory:
    required: false
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5

    - run: |
        go install golang.org/x/lint/golint@latest
        golint ./...
      shell: bash
      working-directory: ${{ inputs.working-directory }}
