name: Java CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/**
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    uses: './.github/workflows/ci.yml'
    with:
      working-directory: '.'
      environment: 'dev'
