name: "Notification Delegator"
description: "Sends notifications via Slack, Discord, or Email"

inputs:
  method:
    required: true
    description: string
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: Notify Slack
      if: ${{ inputs.method == 'slack' }}
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "${{ inputs.message }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Discord
      if: ${{ inputs.method == 'discord' }}
      uses: Ilshidur/action-discord@v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: ${{ inputs.message }}

    - name: Notify Email
      if: ${{ inputs.method == 'email' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "CI/CD Notification"
        body: ${{ inputs.message }}
        to: ${{ secrets.EMAIL_TO }}
        from: "ci-cd@yourdomain.com"

    - name: Skipped
      if: ${{ !contains('slack,discord,email', inputs.method) }}
      run: echo "No notification method configured for ${{ inputs.method }}."
      shell: bash
