name: "Notification Delegator"
description: "Sends notifications via Discord, Slack, Email, MS Teams, PagerDuty"

inputs:
  method:
    required: true
    description: string
  message:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - name: Notify Discord
      if: ${{ inputs.method == 'discord' }}
      uses: ./notify-discord
      with:
        message: ${{ inputs.message }}

    - name: Notify Slack
      if: ${{ inputs.method == 'slack' }}
      uses: ./notify-slack
      with:
        message: ${{ inputs.message }}

    - name: Notify Email
      if: ${{ inputs.method == 'email' }}
      uses: ./notify-email
      with:
        message: ${{ inputs.message }}

    - name: Notify MS Teams
      if: ${{ inputs.method == 'ms-team' }}
      uses: ./notify-ms-teams
      with:
        message: ${{ inputs.message }}

    - name: PagerDuty Alert
      if: ${{ inputs.method == 'pagerduty' }}
      uses: ./notify-pagerduty
      with:
        message: ${{ inputs.message }}

    - name: Notification fallback
      if: ${{ !contains('discord,slack,email,ms-team,pagerduty', inputs.method) }}
      run: echo "No notification method configured for ${{ inputs.method }}."
      shell: bash
