name: Blue-Green Deployment

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      green-svc:
        required: true
        type: string
      blue-svc:
        required: true
        type: string

jobs:
  blue-green:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Green
        run: |
          kubectl set image deployment/${{ inputs.green-svc }} ${{ inputs.service-name }}=${{ inputs.image }}:${{ inputs.tag }}
      - name: Health check Green
        run: curl -f http://${{ inputs.green-svc }}/health
      - name: Switch traffic to Green
        run: |
          kubectl patch service/${{ inputs.service-name }} -p '{"spec":{"selector":{"app":"${{ inputs.green-svc }}"}}}'
