name: Deploy With Automated Rollback

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      healthcheck-url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new version
        run: |
          kubectl set image deployment/${{ inputs.service-name }} ${{ inputs.service-name }}=${{ inputs.image }}:${{ inputs.tag }}
      - name: Wait for rollout
        run: kubectl rollout status deployment/${{ inputs.service-name }} --timeout=2m
      - name: Health check
        id: health
        run: |
          sleep 10
          curl -f ${{ inputs.healthcheck-url }}
      - name: Rollback if health check fails
        if: failure() && steps.health.outcome == 'failure'
        run: |
          kubectl rollout undo deployment/${{ inputs.service-name }}

