name: Deploy Delegator

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      strategy:
        required: false
        default: 'rolling'
        type: string
      platform:
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/actions/deploy
    with:
      environment: ${{ inputs.environment }}
      image-tag: ${{ inputs.image-tag }}
      strategy: ${{ inputs.strategy }}
      platform: ${{ inputs.platform }}
