name: Shadow Deployment

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      image:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  shadow:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy shadow version
        run: |
          kubectl set image deployment/${{ inputs.service-name }}-shadow ${{ inputs.service-name }}=${{ inputs.image }}:${{ inputs.tag }}
      - name: Mirror traffic (service mesh control here)
        run: |
          echo "Set up shadow traffic mirroring via service mesh (e.g. Istio, Linkerd)"
