name: "DataDog Monitoring"
description: "Sends deployment notification to DataDog"

inputs:
  app-path:
    required: false
    description: string

runs:
  using: "composite"
  steps:
    - name: DataDog Deployment Marker
      uses: DataDog/datadog-actions/monitor-notify@v1
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
        app-key: ${{ secrets.DATADOG_APP_KEY }}
        message: "Deployment monitoring started for ${{ github.repository }}"