name: "Lint Delegator"
description: "Delegates linting based on language"

inputs:
  app-path:
    required: true
    description: string
  language:
    required: true
    description: string
  framework:
    required: false
    description: string

runs:
  using: "composite"
  steps:
    - name: Lint Next.js
      if: ${{ contains(inputs.framework, 'nextjs') }}
      uses: ./lint-nextjs

    - name: Lint Nuxt.js
      if: ${{ contains(inputs.framework, 'nuxtjs') }}
      uses: ./lint-nuxtjs

    - name: Lint JS/TS
      if: ${{ (inputs.language == 'javascript' || inputs.language == 'typescript') && !contains(inputs.framework, 'nextjs') && !contains(inputs.framework, 'nuxtjs') }}
      uses: ./lint-js

    - name: Lint fallback
      if: ${{ !contains('nextjs,nuxtjs', inputs.framework) && !(inputs.language == 'javascript' || inputs.language == 'typescript') }}
      run: echo "No linter configured for ${{ inputs.framework }} (${{ inputs.language }})."
      shell: bash
