name: "Lint Dispatcher"
description: "Delegates linting based on language"

inputs:
  app-path:
    required: true
    description: string
  language:
    required: true
    description: string
  framework:
    required: false
    description: string

runs:
  using: "composite"
  steps:
    - name: Lint Python
      if: ${{ inputs.language == 'python' }}
      uses: ./lint-python
      with:
        app-path: ${{ inputs.app-path }}

    - name: Lint Java
      if: ${{ inputs.language == 'java' }}
      uses: ./lint-java
      with:
        app-path: ${{ inputs.app-path }}

    - name: Lint Go
      if: ${{ inputs.language == 'go' }}
      uses: ./lint-go
      with:
        app-path: ${{ inputs.app-path }}

    - name: Lint Node.js
      if: ${{ inputs.language == 'node' || inputs.language == 'javascript' || inputs.language == 'typescript' }}
      uses: ./lint-node
      with:
        app-path: ${{ inputs.app-path }}

    - name: Lint Rust
      if: ${{ inputs.language == 'rust' }}
      uses: ./lint-rust
      with:
        app-path: ${{ inputs.app-path }}

    - name: Lint fallback
      if: ${{ !contains('python,java,go,node,javascript,typescript,rust', inputs.language) }}
      run: echo "No linter configured for ${{ inputs.language }}."
      shell: bash

