name: nuxtjs-app
type: frontend
framework: nuxtjs
language: javascript
ci: true
cd: true
test: true
build: true
deploy:
  enabled: true
  platform: kubernetes
  strategy: rolling
environment: staging
