name: "Lint Nuxt.js"
description: "Lints a Nuxt.js app"

inputs:
  app-path:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.app-path }}"
        npm ci
        npx eslint . --ext .js,.ts,.vue
      shell: bash
