name: Monitor - New Relic

on:
  workflow_call:
    inputs:
      workflow-name:
        required: true
        type: string
      job-status:
        required: true
        type: string
      environment:
        required: true
        type: string
      newrelic-api-key:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify New Relic
        run: |
          curl -X POST "https://insights-collector.newrelic.com/v1/accounts/YOUR_ACCOUNT_ID/events" \
            -H "Content-Type: application/json" \
            -H "X-Insert-Key: ${{ inputs.newrelic-api-key }}" \
            -d '{
              "eventType": "GitHubAction",
              "workflow": "${{ inputs.workflow-name }}",
              "status": "${{ inputs.job-status }}",
              "environment": "${{ inputs.environment }}"
            }'
