name: "New Relic Monitoring"
description: "Sends deployment marker to New Relic"

inputs:
  app-path:
    required: false
    description: string

runs:
  using: "composite"
  steps:
    - name: New Relic Deployment Marker
      uses: newrelic/deployment-marker-action@v3
      with:
        apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
        appName: ${{ github.repository }}
        revision: ${{ github.sha }}