name: "Build Rust Docker Image"
description: "Builds and pushes Docker image for Rust app"

inputs:
  app-path:
    required: true
    description: string
  image-name:
    required: true
    description: string
  tag:
    required: false
    description: string
    default: "latest"

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.app-path }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
