name: Multi-Cloud Multi-Region CD

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string

jobs:
  deploy-matrix:
    strategy:
      matrix:
        include:
          - platform: eks
            region: us-east-1
            cluster_name: "eks-prod"
          - platform: gke
            region: us-central1
            cluster_name: "gke-prod"
            project_id: "gke-prod"
          - platform: aks
            region: eastus
            cluster_name: "aks-prod"
            resource_group: "your-aks-resource-group"
    uses: ./.github/templates/cd.yml
    with:
      app-path: ${{ github.event.inputs.app-path }}
      platform: ${{ matrix.platform }}
      region: ${{ matrix.region }}
      cluster_name: ${{ matrix.cluster_name }}
      project_id: ${{ matrix.project_id }}
      resource_group: ${{ matrix.resource_group }}


