name: Lint Rust
description: "Lints Rust code using cargo clippy"

inputs:
  app-path:
    required: true
    description: string

runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.app-path }}"
        cargo clippy --all-targets --all-features -- -D warnings
      shell: bash
