name: Reusable CD Template

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string
      platform:
        required: true
        type: string
      region:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      project_id:
        required: false
        type: string
      resource_group:
        required: false
        type: string

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.config.outputs.name }}
      language: ${{ steps.config.outputs.language }}
      deploy_enabled: ${{ steps.config.outputs.deploy_enabled }}
      deploy_platform: ${{ steps.config.outputs.deploy_platform }}
      environment: ${{ steps.config.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Read app config
        id: config
        uses: ./.github/actions/app-config
        with:
          app-path: ${{ inputs.app-path }}

    deploy:
      needs: read-config
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/deploy
          with:
            platform: ${{ inputs.platform }}
            app-path: ${{ inputs.app-path }}
            image-name: ${{ needs.read-config.outputs.name }}
            tag: "latest"
            environment: ${{ needs.read-config.outputs.environment }}
            region: ${{ inputs.region }}
            cluster_name: ${{ inputs.cluster_name }}
            project_id: ${{ inputs.project_id }}
            resource_group: ${{ inputs.resource_group }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ always() && needs.read-config.outputs.deploy_enabled == 'true' }}
    steps:
      - uses: ./.github/actions/notify
        with:
          method: ${{ needs.read-config.outputs.notify_method || 'slack' }}
          message: "Deployed ${{ needs.read-config.outputs.name }} to ${{ needs.read-config.outputs.deploy_platform }} (${{ needs.read-config.outputs.environment }})"

