name: CD Template with with reusable workflows

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.config.outputs.name }}
      deploy_enabled: ${{ steps.config.outputs.deploy_enabled }}
      deploy_platform: ${{ steps.config.outputs.deploy_platform }}
      deploy_strategy: ${{ steps.config.outputs.deploy_strategy }}
      environment: ${{ steps.config.outputs.environment }}
      notify_method: ${{ steps.config.outputs.notify_method }}
    steps:
      - uses: actions/checkout@v4
      - name: Read app config
        id: config
        uses: ./.github/actions/app-config
        with:
          app-path: ${{ inputs.app-path }}

  deploy:
    needs: read-config
    runs-on: ubuntu-latest
    if: ${{ needs.read-config.outputs.deploy_enabled == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.read-config.outputs.name }}-build
      - uses: ./.github/actions/build-image
        with:
          app-path: ${{ inputs.app-path }}
          image-name: ${{ needs.read-config.outputs.name }}
      - uses: ./.github/actions/deploy
        with:
          platform: ${{ needs.read-config.outputs.deploy_platform }}
          app-path: ${{ inputs.app-path }}
          image-name: ${{ needs.read-config.outputs.name }}
          environment: ${{ needs.read-config.outputs.environment }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ needs.read-config.outputs.deploy_enabled == 'true' }}
    steps:
      - uses: ./.github/actions/notify
        with:
          method: ${{ needs.read-config.outputs.notify_method }}
          message: "Deployed ${{ needs.read-config.outputs.name }} to ${{ needs.read-config.outputs.deploy_platform }} (${{ needs.read-config.outputs.environment }})"
