name: Reusable CI Template

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.config.outputs.name }}
      framework: ${{ steps.config.outputs.framework }}
      language: ${{ steps.config.outputs.language }}
      lint: ${{ steps.config.outputs.lint }}
      test: ${{ steps.config.outputs.test }}
      build: ${{ steps.config.outputs.build }}
    steps:
      - uses: actions/checkout@v4
      - name: Read app config
        id: config
        uses: ./.github/actions/app-config
        with:
          app-path: ${{ inputs.app-path }}

  lint:
    needs: read-config
    runs-on: ubuntu-latest
    if: ${{ needs.read-config.outputs.lint == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint
        with:
          app-path: ${{ inputs.app-path }}
          language: ${{ needs.read-config.outputs.language }}
          framework: ${{ needs.read-config.outputs.framework }}

  test:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ needs.read-config.outputs.test == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with:
          app-path: ${{ inputs.app-path }}
          language: ${{ needs.read-config.outputs.language }}
          framework: ${{ needs.read-config.outputs.framework }}

  build:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.read-config.outputs.build == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-image
        with:
          app-path: ${{ inputs.app-path }}
          image-name: ${{ needs.read-config.outputs.name }}
          language: ${{ needs.read-config.outputs.language }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.read-config.outputs.name }}-build
          path: ${{ inputs.app-path }}

